### ISSUE TITLE
项目还在开发中吗

### ISSUE THREAD

**Issue by zaaach** [TakWolf/Android-MarkdownTextView#1]

**Comment by TakWolf** [comment]
项目已经停止开发了。
原生控件渲染Markdown有致命缺陷，请考虑使用WebView实现Markdown渲染。

**Comment by TakWolf** [comment]
另外，请参考bilibili的drawee-text-view来实现原生控件的图文混排

https://github.com/Bilibili/drawee-text-view

**Comment by zaaach** [comment]
恩好，谢谢啦
